# Generated by Django 3.0.8 on 2020-07-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreepingAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', null=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=60, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Ползучий зверь',
                'verbose_name_plural': 'Ползучие звери',
            },
        ),
        migrations.CreateModel(
            name='FlyingAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', null=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Летающий зверь',
                'verbose_name_plural': 'Летающие звери',
            },
        ),
        migrations.CreateModel(
            name='ShaggyAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', null=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('count_teeth', models.IntegerField(verbose_name='Количество зубов')),
            ],
            options={
                'verbose_name': 'Мохнатый зверь',
                'verbose_name_plural': 'Мохнатые зверушки',
            },
        ),
        migrations.CreateModel(
            name='WaterfowlAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', null=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Водоплавающий зверь',
                'verbose_name_plural': 'Водоплавающие звери',
            },
        ),
        migrations.CreateModel(
            name='WaterfowlAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.DecimalField(decimal_places=2, help_text='Измеряется в см.', max_digits=5, verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Измеряется в кг.', max_digits=10, verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.WaterfowlAnimal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Учет водоплавающих',
                'verbose_name_plural': 'Учет водоплавающих',
            },
        ),
        migrations.CreateModel(
            name='ShaggyAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.DecimalField(decimal_places=2, help_text='Измеряется в см.', max_digits=5, verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Измеряется в кг.', max_digits=10, verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.ShaggyAnimal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Учет мохнатых',
                'verbose_name_plural': 'Учет мохнатых',
            },
        ),
        migrations.CreateModel(
            name='FlyingAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.DecimalField(decimal_places=2, help_text='Измеряется в см.', max_digits=5, verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Измеряется в кг.', max_digits=10, verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.FlyingAnimal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Учет летающих',
                'verbose_name_plural': 'Учет летающих',
            },
        ),
        migrations.CreateModel(
            name='CreepingAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.DecimalField(decimal_places=2, help_text='Измеряется в см.', max_digits=5, verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Измеряется в кг.', max_digits=10, verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CreepingAnimal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Учет ползучих',
                'verbose_name_plural': 'Учет ползучих',
            },
        ),
    ]
