# Generated by Django 3.0.8 on 2020-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20200708_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='creepingaccounting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='flyingaccounting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='shaggyaccounting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='waterfowlaccounting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='creepinganimal',
            name='date_birthday',
            field=models.DateField(auto_created=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='flyinganimal',
            name='date_birthday',
            field=models.DateField(auto_created=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='shaggyanimal',
            name='date_birthday',
            field=models.DateField(auto_created=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='waterfowlanimal',
            name='date_birthday',
            field=models.DateField(auto_created=True, verbose_name='Дата рождения'),
        ),
    ]
