# Generated by Django 3.0.8 on 2020-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20200708_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaggyanimal',
            name='count_teeth',
            field=models.IntegerField(),
        ),
    ]
