# Generated by Django 3.0.8 on 2020-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20200709_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='creepinganimal',
            name='animal_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='flyinganimal',
            name='animal_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='shaggyanimal',
            name='animal_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='waterfowlanimal',
            name='animal_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Имя'),
        ),
    ]
